// <auto-generated />
using System;
using AddisMedConnect.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AddisMedConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AddisDbContext))]
    [Migration("20260824185448_RestoreAmbulanceLocation")]
    partial class RestoreAmbulanceLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AddisMedConnect.Domain.Entities.Bed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentCaseId")
                        .HasColumnType("text");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastStatusUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCaseId")
                        .IsUnique();

                    b.HasIndex("HospitalId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("AddisMedConnect.Domain.Entities.EmergencyCase", b =>
                {
                    b.Property<string>("IncidentNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("AssignedAmbulanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedBedId")
                        .HasColumnType("uuid");

                    b.Property<string>("CallerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IncidentReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupAddress")
                        .HasColumnType("text");

                    b.Property<double?>("PickupLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("PickupLongitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetHospitalId")
                        .HasColumnType("uuid");

                    b.HasKey("IncidentNumber");

                    b.HasIndex("AssignedAmbulanceId");

                    b.HasIndex("TargetHospitalId");

                    b.ToTable("EmergencyCases");
                });

            modelBuilder.Entity("AddisMedConnect.Domain.Entities.Hospital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("AddisMedConnect.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedHospitalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedHospitalId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ambulance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CurrentLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CurrentLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("DriverName")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ambulances");
                });

            modelBuilder.Entity("AddisMedConnect.Domain.Entities.Bed", b =>
                {
                    b.HasOne("AddisMedConnect.Domain.Entities.EmergencyCase", "CurrentCase")
                        .WithOne("AssignedBed")
                        .HasForeignKey("AddisMedConnect.Domain.Entities.Bed", "CurrentCaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AddisMedConnect.Domain.Entities.Hospital", "Hospital")
                        .WithMany("Beds")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentCase");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("AddisMedConnect.Domain.Entities.EmergencyCase", b =>
                {
                    b.HasOne("Ambulance", "AssignedAmbulance")
                        .WithMany()
                        .HasForeignKey("AssignedAmbulanceId");

                    b.HasOne("AddisMedConnect.Domain.Entities.Hospital", "TargetHospital")
                        .WithMany("DestinationCases")
                        .HasForeignKey("TargetHospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedAmbulance");

                    b.Navigation("TargetHospital");
                });

            modelBuilder.Entity("AddisMedConnect.Domain.Entities.User", b =>
                {
                    b.HasOne("AddisMedConnect.Domain.Entities.Hospital", "AssignedHospital")
                        .WithMany("Staff")
                        .HasForeignKey("AssignedHospitalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedHospital");
                });

            modelBuilder.Entity("AddisMedConnect.Domain.Entities.EmergencyCase", b =>
                {
                    b.Navigation("AssignedBed");
                });

            modelBuilder.Entity("AddisMedConnect.Domain.Entities.Hospital", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("DestinationCases");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
